---
- name: update cache
  apt:
    update_cache: yes
    # upgrade: dist
  when: apt.all_update_flag

- name: upgrade all packages
  apt:
    name: '*'
    state: latest
  when: apt.all_upgrade_flag

- name: install apt packages
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    # update_cache: yes
    cache_valid_time: 3600
  with_items: '{{ apt.packages }}'
  when: apt.packages is defined
